apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ued0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-ued0@sha256:86a5df282d4dbbfcc3af5442e2a1ba610760c75bec5e5c5a661189f8891c6b55
        name: my-nodejs
        resources: {}
status: {}
